version: '3.8'
services:
  # redis:
  #   image: 'redis:latest'
  #   ports:
  #     - 6379:6379
  postg-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticket_app
    networks:
      - nettt
networks:
  nettt:
